"""create events table

Revision ID: aaf745cd33e9
Revises: ffdc0a98111c
Create Date: 2021-05-23 19:23:08.146875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf745cd33e9'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventId_x', sa.Integer(), nullable=True),
    sa.Column('subEventName', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.PickleType(), nullable=True),
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.Column('positions', sa.PickleType(), nullable=True),
    sa.Column('matchId', sa.Integer(), nullable=True),
    sa.Column('eventName', sa.String(length=255), nullable=True),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('matchPeriod', sa.String(length=255), nullable=True),
    sa.Column('eventSec', sa.Float(), nullable=True),
    sa.Column('gameWeek', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.Column('wyId', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('firstName', sa.String(length=255), nullable=True),
    sa.Column('middleName', sa.String(length=255), nullable=True),
    sa.Column('lastName', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
