"""changed foreign key from comments to matches

Revision ID: 7a24a3d798b2
Revises: 7812fa0ad08d
Create Date: 2021-06-09 15:44:49.325729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a24a3d798b2'
down_revision = '7812fa0ad08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_match_key_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'matches', ['match_key'], ['match_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_match_key_fkey', 'comments', 'matches', ['match_key'], ['id'])
    # ### end Alembic commands ###
