"""fixed foreignkey between matches and events

Revision ID: 9a062d19d38c
Revises: c5479344dbe9
Create Date: 2021-06-02 15:53:01.950867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a062d19d38c'
down_revision = 'c5479344dbe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'matches', ['match_key'])
    op.create_foreign_key(None, 'comments', 'matches', ['match_id'], ['id'])
    op.create_foreign_key(None, 'events', 'matches', ['match_id'], ['match_key'])
    op.create_foreign_key(None, 'favorites', 'matches', ['match_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='unique')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
