"""empty message

Revision ID: 90bd707286d6
Revises: 
Create Date: 2021-06-01 18:39:16.999993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bd707286d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventId_x', sa.Integer(), nullable=True),
    sa.Column('subEventName', sa.String(length=255), nullable=True),
    sa.Column('tag1', sa.Numeric(), nullable=True),
    sa.Column('tag2', sa.Numeric(), nullable=True),
    sa.Column('tag3', sa.Numeric(), nullable=True),
    sa.Column('tag4', sa.Numeric(), nullable=True),
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.Column('xStart', sa.Integer(), nullable=True),
    sa.Column('yStart', sa.Integer(), nullable=True),
    sa.Column('xEnd', sa.Integer(), nullable=True),
    sa.Column('yEnd', sa.Integer(), nullable=True),
    sa.Column('matchId', sa.Integer(), nullable=True),
    sa.Column('eventName', sa.String(length=255), nullable=True),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('matchPeriod', sa.String(length=255), nullable=True),
    sa.Column('eventSec', sa.Numeric(), nullable=True),
    sa.Column('gameWeek', sa.Integer(), nullable=True),
    sa.Column('dateutc', sa.String(length=255), nullable=True),
    sa.Column('wyId', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('firstName', sa.String(length=255), nullable=True),
    sa.Column('middleName', sa.String(length=255), nullable=True),
    sa.Column('lastName', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('events')
    # ### end Alembic commands ###
