"""added match images

Revision ID: 7a35434facb6
Revises: efe0c1fb83ab
Create Date: 2021-06-07 15:30:14.268644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a35434facb6'
down_revision = 'efe0c1fb83ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'match_img')
    # ### end Alembic commands ###
