"""empty message

Revision ID: ee93fa9df840
Revises: 663f8d99417b
Create Date: 2021-06-04 11:26:31.966975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee93fa9df840'
down_revision = '663f8d99417b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_name', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'matches', ['match_name'])
    op.create_foreign_key(None, 'events', 'matches', ['label'], ['match_name'])
    op.drop_column('events', 'wy_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_label_fkey', 'events', type_='foreignkey')
    op.drop_constraint('matches_match_name_key', 'matches', type_='unique')
    op.drop_column('matches', 'match_name')
    op.add_column('events', sa.Column('wy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
