"""deleted event_id_x, game_week, and match_period columns

Revision ID: efe0c1fb83ab
Revises: cb93ca66aaf0
Create Date: 2021-06-06 21:08:20.602006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe0c1fb83ab'
down_revision = 'cb93ca66aaf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_id_x')
    op.drop_column('events', 'match_period')
    op.drop_column('events', 'game_week')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('game_week', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('match_period', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('event_id_x', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
