"""added team color

Revision ID: 71c7158a6f35
Revises: 7a24a3d798b2
Create Date: 2021-06-13 20:36:52.509029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c7158a6f35'
down_revision = '7a24a3d798b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('team_color', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'team_color')
    # ### end Alembic commands ###
