"""changed matchkey on favorites table

Revision ID: 7812fa0ad08d
Revises: 60ebedc0328e
Create Date: 2021-06-09 13:18:30.022680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7812fa0ad08d'
down_revision = '60ebedc0328e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('match_key', sa.Integer(), nullable=False))
    op.drop_constraint('comments_match_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'matches', ['match_key'], ['id'])
    op.drop_column('comments', 'match_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_match_id_fkey', 'comments', 'matches', ['match_id'], ['id'])
    op.drop_column('comments', 'match_key')
    # ### end Alembic commands ###
